#!/usr/bin/env python3
"""
PyManager CI/CD Generator
Auto-generate GitHub Actions, GitLab CI, and other CI/CD configs
"""

from pathlib import Path
from typing import Dict


class CICDGenerator:
    """Generate CI/CD pipeline configurations"""

    def __init__(self, config: Dict):
        self.config = config

    def generate_github_actions(self, python_versions: list = ['3.9', '3.10', '3.11']) -> str:
        """Generate GitHub Actions workflow"""
        versions_yaml = '\n        '.join([f"- '{v}'" for v in python_versions])

        return f"""# Auto-generated by PyManager
name: Python Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        {versions_yaml}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{{{ matrix.python-version }}}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{{{ matrix.python-version }}}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: Run tests
      run: |
        if [ -f pytest.ini ] || [ -d tests ]; then
          pytest
        else
          echo "No tests found"
        fi

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
"""

    def generate_gitlab_ci(self, python_version: str = '3.11') -> str:
        """Generate GitLab CI config"""
        return f"""# Auto-generated by PyManager
image: python:{python_version}

stages:
  - test
  - deploy

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest --cov=.
  coverage: '/TOTAL.*\\s+(\\d+%)$/'

lint:
  stage: test
  script:
    - pip install flake8
    - flake8 .

deploy:
  stage: deploy
  script:
    - echo "Deploy steps here"
  only:
    - main
"""

    def setup_cicd(self, project_dir: Path, platform: str = 'github'):
        """Setup CI/CD for project"""
        if platform == 'github':
            github_dir = project_dir / '.github' / 'workflows'
            github_dir.mkdir(parents=True, exist_ok=True)

            workflow_file = github_dir / 'python-tests.yml'
            workflow_file.write_text(self.generate_github_actions())
            print(f"✅ Created GitHub Actions workflow: {workflow_file}")

        elif platform == 'gitlab':
            gitlab_file = project_dir / '.gitlab-ci.yml'
            gitlab_file.write_text(self.generate_gitlab_ci())
            print(f"✅ Created GitLab CI config: {gitlab_file}")

        print(f"\n🚀 CI/CD setup complete for {platform}")


def main():
    import argparse

    parser = argparse.ArgumentParser(description='PyManager CI/CD Generator')
    parser.add_argument('--path', type=str, default='.', help='Project path')
    parser.add_argument('--platform', choices=['github', 'gitlab'], default='github',
                        help='CI/CD platform')

    args = parser.parse_args()

    generator = CICDGenerator({})
    generator.setup_cicd(Path(args.path), args.platform)


if __name__ == '__main__':
    main()
