#!/usr/bin/env python3
"""
PyManager Docker Generator
Auto-generate Dockerfiles for Python projects
"""

from pathlib import Path
from typing import Dict, Optional


class DockerGenerator:
    """Generate Dockerfiles for Python projects"""

    def __init__(self, config: Dict):
        self.config = config

    def generate_dockerfile(self, project_dir: Path, python_version: str = '3.11',
                           requirements_file: Optional[Path] = None) -> str:
        """Generate Dockerfile content"""

        req_file = requirements_file or project_dir / 'requirements.txt'
        has_requirements = req_file.exists()

        dockerfile = f"""# Auto-generated by PyManager
FROM python:{python_version}-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
"""

        if has_requirements:
            dockerfile += f"""COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

"""

        dockerfile += """# Copy application code
COPY . .

# Run application
CMD ["python", "main.py"]
"""

        return dockerfile

    def generate_dockerignore(self) -> str:
        """Generate .dockerignore content"""
        return """# PyManager auto-generated .dockerignore
__pycache__
*.pyc
*.pyo
*.pyd
.Python
*.so
*.egg
*.egg-info
dist
build
.venv
venv
env
.env
.git
.gitignore
.dockerignore
Dockerfile
*.log
.cache
.pytest_cache
.mypy_cache
"""

    def generate_compose(self, project_name: str, python_version: str = '3.11') -> str:
        """Generate docker-compose.yml"""
        return f"""# Auto-generated by PyManager
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: {project_name}:latest
    container_name: {project_name}
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
"""

    def setup_docker(self, project_dir: Path, python_version: str = '3.11'):
        """Create all Docker files for project"""
        project_name = project_dir.name

        # Generate Dockerfile
        dockerfile = project_dir / 'Dockerfile'
        dockerfile.write_text(self.generate_dockerfile(project_dir, python_version))
        print(f"✅ Created Dockerfile")

        # Generate .dockerignore
        dockerignore = project_dir / '.dockerignore'
        dockerignore.write_text(self.generate_dockerignore())
        print(f"✅ Created .dockerignore")

        # Generate docker-compose.yml
        compose = project_dir / 'docker-compose.yml'
        compose.write_text(self.generate_compose(project_name, python_version))
        print(f"✅ Created docker-compose.yml")

        print(f"\n📦 Docker setup complete for {project_name}")
        print(f"\nBuild and run:")
        print(f"  docker-compose up --build")


def main():
    import argparse
    import json

    parser = argparse.ArgumentParser(description='PyManager Docker Generator')
    parser.add_argument('--path', type=str, default='.', help='Project path')
    parser.add_argument('--version', type=str, default='3.11', help='Python version')

    args = parser.parse_args()

    config = {}
    generator = DockerGenerator(config)
    generator.setup_docker(Path(args.path), args.version)


if __name__ == '__main__':
    main()
